c = (input('digite algo:'))
print('o tipo primitivo é {}'.format((type(c))))
print('é alfabético?', c.isalpha())
print('é numérico?', c.isnumeric())
print('é alfanumerico?', c.isalnum())
print('só tem espaço?', c.isspace())
print('está em minúscula?', c.islower())
print('está em maiúscula?', c.isupper())
print('está capitalizada?', c.istitle())
